#ifndef clox_scanner_h
#define clox_scanner_h

typedef enum {
  // Control flow
  TOKEN_LEFT_PAREN, TOKEN_RIGHT_PAREN,
  TOKEN_LEFT_BRACE, TOKEN_RIGHT_BRACE,
  TOKEN_LEFT_BRACKET, TOKEN_RIGHT_BRACKET,
  TOKEN_COMMA, TOKEN_DOT, TOKEN_SEMICOLON,
  TOKEN_DOLLAR,
  
  // Operators
  TOKEN_INC, TOKEN_DEC,
  TOKEN_MINUS, TOKEN_PLUS,
  TOKEN_SLASH, TOKEN_STAR, TOKEN_MODULO,
  TOKEN_AND, TOKEN_BIT_AND,
  TOKEN_OR, TOKEN_BIT_OR,
  TOKEN_BIT_XOR,
  TOKEN_BANG, TOKEN_BANG_EQUAL,
  TOKEN_EQUAL, TOKEN_EQUAL_EQUAL,
  TOKEN_GREATER, TOKEN_GREATER_EQUAL,
  TOKEN_LESS, TOKEN_LESS_EQUAL,
  TOKEN_COMPARE,
  TOKEN_L_SHIFT, TOKEN_R_SHIFT, 
  TOKEN_AT,
  TOKEN_QMARK_QMARK, TOKEN_QMARK, TOKEN_COLON, TOKEN_COLON_COLON,
  TOKEN_HASH,

  // Literals.
  TOKEN_IDENTIFIER, TOKEN_STRING, TOKEN_CHAR, TOKEN_FLT, TOKEN_INT, TOKEN_FIX,

  // Keywords.
  TOKEN_INTERFACE, TOKEN_ABSTRACT, TOKEN_CLASS, TOKEN_STRUCT, TOKEN_ENUM,
  TOKEN_HEAP, TOKEN_STACK, TOKEN_MARK, TOKEN_DELETE,
  TOKEN_IF, TOKEN_ELSE, TOKEN_FOR, TOKEN_WHILE,
  TOKEN_TRUE, TOKEN_FALSE,
  TOKEN_FUN, TOKEN_VAR, 
  TOKEN_NULL,
  TOKEN_RETURN, TOKEN_SUPER, TOKEN_THIS,
  TOKEN_TRY, TOKEN_CATCH, TOKEN_FINALLY, TOKEN_THROW,
  TOKEN_UNDERSCORE,
  TOKEN_SWITCH, TOKEN_BREAK, TOKEN_CONTINUE,
  TOKEN_ASYNC, TOKEN_AWAIT, TOKEN_SYNC,
  TOKEN_STATIC,

  TOKEN_ERROR, TOKEN_EOF, TOKEN_PRINT
} TokenType;

typedef struct {
  TokenType type;
  const char* start;
  int length;
  int line;
} Token;

void initScanner(const char* source);
Token scanToken();

#endif